# File Converter with SEO Optimization - Configuration
# Operational Manifest and Settings
# Version: 1.0.0
# Last Updated: 2025-10-08

# Application Metadata
app:
  name: "File Converter with SEO Optimization"
  version: "1.0.0"
  description: "Multi-format document converter with SEO enhancement"
  author: "poolboy17"
  license: "MIT"
  repository: "https://github.com/poolboy17/file-converter-seo-app"

# Server Configuration
server:
  host: "0.0.0.0"
  port: 5000
  headless: true
  max_upload_size_mb: 200
  session_timeout_minutes: 30
  enable_cors: false
  allowed_origins: []

# Supported File Formats
formats:
  supported_extensions:
    - docx
    - csv
    - txt
    - wxr
  max_file_size_mb: 50
  batch_processing:
    enabled: true
    max_files_per_batch: 100

# Conversion Settings
conversion:
  default_output_format: "markdown"  # Options: markdown, html, both
  preserve_formatting: true
  extract_metadata: true
  
  # Markdown options
  markdown:
    line_length: null  # null for no wrapping
    code_highlighting: true
    table_support: true
    
  # HTML options
  html:
    default_template: "modern"  # Options: modern, minimal, classic, dark
    default_color_scheme: "blue"  # Options: blue, green, purple, red, orange
    default_font: "default"  # Options: default, sans-serif, serif, monospace
    include_css_inline: true
    responsive_design: true
    minify_output: false

# Image Processing
images:
  extraction:
    enabled: true
    from_docx: true
    from_wxr: true
  
  optimization:
    enabled: true
    max_width_px: 1200
    max_height_px: 1200
    jpeg_quality: 85
    png_compression: 6
    webp_enabled: false
  
  deduplication:
    enabled: true
    hash_algorithm: "md5"
  
  download:
    timeout_seconds: 30
    max_retries: 3
    user_agent: "FileConverter/1.0"
    verify_ssl: true
  
  storage:
    assets_folder: "assets"
    image_subfolder: "images"
    relative_paths: true

# SEO Configuration
seo:
  validation:
    enabled: true
    strict_mode: false
    
  enhancement:
    enabled_by_default: true
    auto_inject_meta_tags: true
    add_open_graph: true
    add_twitter_cards: true
    add_schema_org: true
    add_canonical_url: true
    semantic_html: true
    
  scoring:
    title_tag:
      weight: 15
      optimal_min_length: 30
      optimal_max_length: 60
    meta_description:
      weight: 15
      optimal_min_length: 120
      optimal_max_length: 160
    heading_structure:
      weight: 10
    image_alt_text:
      weight: 10
    link_quality:
      weight: 10
    content_length:
      weight: 15
      minimum_words: 300
    open_graph:
      weight: 15
    structured_data:
      weight: 10
  
  grading:
    grade_a_threshold: 90
    grade_b_threshold: 80
    grade_c_threshold: 70
    grade_d_threshold: 60

# Static Site Generation
static_site:
  enabled: true
  default_site_name: "My Converted Documents"
  
  structure:
    pages_folder: "pages"
    assets_folder: "assets"
    css_folder: "assets"
    
  navigation:
    show_index: true
    show_breadcrumbs: false
    show_file_count: true
    
  frontmatter:
    generators:
      - jekyll
      - hugo
      - astro
    include_date: true
    include_author: true
    include_categories: true
    default_author: "Anonymous"

# Templates
templates:
  styles:
    - name: "modern"
      description: "Clean, contemporary design"
    - name: "minimal"
      description: "Simple, distraction-free"
    - name: "classic"
      description: "Traditional document style"
    - name: "dark"
      description: "Dark mode optimized"
  
  color_schemes:
    - name: "blue"
      primary: "#2563eb"
    - name: "green"
      primary: "#059669"
    - name: "purple"
      primary: "#7c3aed"
    - name: "red"
      primary: "#dc2626"
    - name: "orange"
      primary: "#ea580c"

# File Packaging
packaging:
  zip:
    enabled: true
    compression_level: 6  # 0-9, higher = more compression
    include_metadata: true
    
  output:
    preserve_structure: true
    include_original_names: true
    timestamp_format: "%Y%m%d_%H%M%S"

# Feature Flags
features:
  batch_conversion: true
  image_extraction: true
  seo_optimization: true
  static_site_generation: true
  frontmatter_generation: true
  template_customization: true
  color_scheme_selection: true
  font_customization: true
  preview_mode: true
  download_individual_files: true
  download_zip_archive: true

# Performance Settings
performance:
  concurrent_conversions: false  # Process files sequentially
  image_lazy_loading: true
  cache_templates: true
  memory_limit_mb: 512
  
# Logging
logging:
  level: "INFO"  # DEBUG, INFO, WARNING, ERROR, CRITICAL
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  log_to_console: true
  log_to_file: false
  log_file_path: null

# Security
security:
  validate_file_types: true
  sanitize_html_output: true
  validate_image_urls: true
  max_url_redirects: 3
  allowed_image_domains: []  # Empty = all domains allowed
  block_private_ips: true
  
# Error Handling
error_handling:
  show_detailed_errors: true
  fallback_encoding: "utf-8"
  ignore_missing_images: false
  continue_on_error: true
  
# UI Configuration
ui:
  theme: "light"  # light or dark
  show_file_preview: true
  preview_max_length: 1000
  show_conversion_progress: true
  sidebar_collapsed: false
  tabs:
    - "File List"
    - "Preview"
    - "Download"
    - "SEO Report"
  
# Deployment
deployment:
  environment: "production"  # development, staging, production
  platform: "replit"  # replit, docker, heroku, custom
  
  health_check:
    enabled: false
    endpoint: "/health"
    
  monitoring:
    enabled: false
    
  scaling:
    min_instances: 1
    max_instances: 1
    
# External Services (if any)
external_services:
  cdn:
    enabled: false
    url: null
    
  storage:
    type: "local"  # local, s3, gcs, azure
    
# Maintenance
maintenance:
  mode: false
  message: "System under maintenance. Please try again later."
  
# Rate Limiting (for future implementation)
rate_limiting:
  enabled: false
  requests_per_minute: 60
  requests_per_hour: 1000
  
# API Configuration (for future API endpoint)
api:
  enabled: false
  version: "v1"
  base_path: "/api/v1"
  authentication_required: false
  
# Experimental Features
experimental:
  pdf_support: false
  rtf_support: false
  ai_content_enhancement: false
  multi_language_support: false
  real_time_collaboration: false
  
# Compatibility
compatibility:
  python_version: "3.11"
  streamlit_version: "1.28.0"
  
# Build Information
build:
  date: "2025-10-08"
  commit: null
  branch: "main"
  
# Support & Contact
support:
  documentation: "https://github.com/poolboy17/file-converter-seo-app/blob/main/README.md"
  issues: "https://github.com/poolboy17/file-converter-seo-app/issues"
  discussions: "https://github.com/poolboy17/file-converter-seo-app/discussions"
